#define 자동 auto
#define 탈출 break
#define 경우 case
#define 상수 const
#define 재개 continue
#define 기본 default
#define 하다 do
#define 또는 else
#define 열거형 enum
#define 외부 extern
#define 되풀이 for
#define 가기 goto
#define 만약 if
#define 즉시정의 inline
#define 등록 register
#define 제한 restrict
#define 반환 return
#define 부호있는 signed
#define 크기의 sizeof
#define 정적 static
#define 구조체 struct
#define 전환 switch
#define 유형정의 typedef
#define 공용체 union
#define 부호없는 unsigned
#define 공허 void
#define 휘발성 volatile
#define 그동안 while
#define 주된 main

#define 문자 char
#define 배정밀도부동소수점수 double
#define 단정밀도부동소수점수 float
#define 정수 int
#define 긴 long
#define 짧은 short
#define 논리값 _Bool
#define 복소수 _Complex
#define 허수 _Imaginary

#define 참 1
#define 거짓 0